<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{c5baf770-4e6d-4c1a-ac95-8140def6c61c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	{attribute 'analysis' := '-33'}
	fbRpcServer : FB_RpcServer;
	
	fbPublisher	: FB_Publisher;		// PubSub example
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
fbPublisher();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>